project:
  type: book
  output-dir: docs

book:
  title: "Álgebra Geométrica para Ciência da Computação"
  author: "Fernando Náufel"
  date: now
  search: true
  repo-url: https://github.com/fnaufel/AG-para-CC
  repo-actions: [edit]
  downloads: [pdf]
  date-format: "DD/MM/YYYY HH:mm"
  chapters:
    - index.qmd
    - intro.qmd
    - prod-externo.qmd
    - references.qmd

bibliography: bibliography.bib

comments:
  hypothesis: true

format:
  html:
    theme: 
      - journal
      - _custom.scss
  pdf:
    documentclass: scrreprt



